version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER =services
      - POSTGRES_PASSWORD =services
      - POSTGRES_DB =services-marketplace
    ports:
      - '5443:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
